import type { Application, Rule, Queue, Analyst } from "./types"

export const mockApplications: Application[] = [
  {
    id: "APP-001",
    reference: "UK-2024-001",
    customerName: "Acme Corporation Ltd",
    country: "United Kingdom",
    numberOfKP: 5,
    numberOfDocuments: 12,
    cashAmount: 250000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 2,
    queryResponseTime: 4,
    customerBehavior: "responsive",
    status: "pending",
    priority: 85,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-002",
    reference: "US-2024-002",
    customerName: "Global Tech Industries",
    country: "United States",
    numberOfKP: 3,
    numberOfDocuments: 8,
    cashAmount: 150000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 6,
    queryResponseTime: 12,
    customerBehavior: "slow",
    status: "pending",
    priority: 45,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-003",
    reference: "UK-2024-003",
    customerName: "Thames Financial Services",
    country: "United Kingdom",
    numberOfKP: 8,
    numberOfDocuments: 25,
    cashAmount: 1500000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 1,
    queryResponseTime: 2,
    customerBehavior: "responsive",
    status: "pending",
    priority: 95,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-004",
    reference: "FR-2024-004",
    customerName: "Paris Trading Group",
    country: "France",
    numberOfKP: 4,
    numberOfDocuments: 10,
    cashAmount: 320000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 8,
    queryResponseTime: 16,
    customerBehavior: "slow",
    status: "pending",
    priority: 40,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-005",
    reference: "UK-2024-005",
    customerName: "London Property Holdings",
    country: "United Kingdom",
    numberOfKP: 12,
    numberOfDocuments: 45,
    cashAmount: 3200000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 3,
    queryResponseTime: 6,
    customerBehavior: "responsive",
    status: "in_progress",
    priority: 98,
    assignedQueue: "Q-004",
    assignedAnalyst: "A-001",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-006",
    reference: "DE-2024-006",
    customerName: "Berlin Manufacturing GmbH",
    country: "Germany",
    numberOfKP: 6,
    numberOfDocuments: 18,
    cashAmount: 580000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 4,
    queryResponseTime: 8,
    customerBehavior: "responsive",
    status: "pending",
    priority: 70,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-007",
    reference: "UK-2024-007",
    customerName: "Manchester Logistics Ltd",
    country: "United Kingdom",
    numberOfKP: 2,
    numberOfDocuments: 6,
    cashAmount: 85000,
    isUKBased: true,
    isComplex: false,
    submissionSpeed: 10,
    queryResponseTime: 20,
    customerBehavior: "poor",
    status: "pending",
    priority: 30,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-008",
    reference: "SG-2024-008",
    customerName: "Singapore Ventures Pte Ltd",
    country: "Singapore",
    numberOfKP: 7,
    numberOfDocuments: 22,
    cashAmount: 890000,
    isUKBased: false,
    isComplex: true,
    submissionSpeed: 5,
    queryResponseTime: 10,
    customerBehavior: "responsive",
    status: "pending",
    priority: 75,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-009",
    reference: "UK-2024-009",
    customerName: "Edinburgh Investment Trust",
    country: "United Kingdom",
    numberOfKP: 15,
    numberOfDocuments: 60,
    cashAmount: 5800000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 2,
    queryResponseTime: 3,
    customerBehavior: "responsive",
    status: "in_progress",
    priority: 99,
    assignedQueue: "Q-004",
    assignedAnalyst: "A-003",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-010",
    reference: "CA-2024-010",
    customerName: "Toronto Capital Group",
    country: "Canada",
    numberOfKP: 3,
    numberOfDocuments: 9,
    cashAmount: 220000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 7,
    queryResponseTime: 14,
    customerBehavior: "slow",
    status: "pending",
    priority: 42,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-011",
    reference: "UK-2024-011",
    customerName: "Bristol Tech Solutions",
    country: "United Kingdom",
    numberOfKP: 4,
    numberOfDocuments: 11,
    cashAmount: 175000,
    isUKBased: true,
    isComplex: false,
    submissionSpeed: 3,
    queryResponseTime: 5,
    customerBehavior: "responsive",
    status: "pending",
    priority: 65,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-012",
    reference: "AU-2024-012",
    customerName: "Sydney Holdings Pty",
    country: "Australia",
    numberOfKP: 5,
    numberOfDocuments: 14,
    cashAmount: 420000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 6,
    queryResponseTime: 11,
    customerBehavior: "responsive",
    status: "pending",
    priority: 68,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-013",
    reference: "UK-2024-013",
    customerName: "Leeds Manufacturing Co",
    country: "United Kingdom",
    numberOfKP: 9,
    numberOfDocuments: 28,
    cashAmount: 1200000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 4,
    queryResponseTime: 7,
    customerBehavior: "responsive",
    status: "pending",
    priority: 88,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 13).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-014",
    reference: "NL-2024-014",
    customerName: "Amsterdam Trade BV",
    country: "Netherlands",
    numberOfKP: 4,
    numberOfDocuments: 12,
    cashAmount: 340000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 9,
    queryResponseTime: 18,
    customerBehavior: "slow",
    status: "pending",
    priority: 38,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-015",
    reference: "UK-2024-015",
    customerName: "Birmingham Retail Group",
    country: "United Kingdom",
    numberOfKP: 6,
    numberOfDocuments: 16,
    cashAmount: 450000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 5,
    queryResponseTime: 9,
    customerBehavior: "responsive",
    status: "completed",
    priority: 78,
    assignedQueue: "Q-001",
    assignedAnalyst: "A-002",
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-016",
    reference: "JP-2024-016",
    customerName: "Tokyo Enterprises KK",
    country: "Japan",
    numberOfKP: 8,
    numberOfDocuments: 24,
    cashAmount: 760000,
    isUKBased: false,
    isComplex: true,
    submissionSpeed: 6,
    queryResponseTime: 12,
    customerBehavior: "responsive",
    status: "pending",
    priority: 72,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-017",
    reference: "UK-2024-017",
    customerName: "Glasgow Investment Partners",
    country: "United Kingdom",
    numberOfKP: 10,
    numberOfDocuments: 35,
    cashAmount: 2100000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 2,
    queryResponseTime: 4,
    customerBehavior: "responsive",
    status: "in_progress",
    priority: 96,
    assignedQueue: "Q-004",
    assignedAnalyst: "A-001",
    createdAt: new Date(Date.now() - 86400000 * 16).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-018",
    reference: "IT-2024-018",
    customerName: "Milan Fashion SpA",
    country: "Italy",
    numberOfKP: 3,
    numberOfDocuments: 8,
    cashAmount: 190000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 11,
    queryResponseTime: 22,
    customerBehavior: "poor",
    status: "pending",
    priority: 28,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 17).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-019",
    reference: "UK-2024-019",
    customerName: "Cardiff Pharmaceutical Ltd",
    country: "United Kingdom",
    numberOfKP: 7,
    numberOfDocuments: 20,
    cashAmount: 680000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 3,
    queryResponseTime: 6,
    customerBehavior: "responsive",
    status: "pending",
    priority: 82,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 18).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-020",
    reference: "US-2024-020",
    customerName: "New York Trading LLC",
    country: "United States",
    numberOfKP: 5,
    numberOfDocuments: 13,
    cashAmount: 380000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 8,
    queryResponseTime: 15,
    customerBehavior: "slow",
    status: "pending",
    priority: 44,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 19).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-021",
    reference: "UK-2024-021",
    customerName: "Newcastle Engineering Works",
    country: "United Kingdom",
    numberOfKP: 11,
    numberOfDocuments: 40,
    cashAmount: 2800000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 2,
    queryResponseTime: 3,
    customerBehavior: "responsive",
    status: "pending",
    priority: 97,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 21).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-022",
    reference: "ES-2024-022",
    customerName: "Barcelona Logistics SA",
    country: "Spain",
    numberOfKP: 4,
    numberOfDocuments: 11,
    cashAmount: 280000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 7,
    queryResponseTime: 13,
    customerBehavior: "slow",
    status: "pending",
    priority: 46,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 22).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-023",
    reference: "UK-2024-023",
    customerName: "Southampton Maritime Services",
    country: "United Kingdom",
    numberOfKP: 3,
    numberOfDocuments: 7,
    cashAmount: 120000,
    isUKBased: true,
    isComplex: false,
    submissionSpeed: 4,
    queryResponseTime: 7,
    customerBehavior: "responsive",
    status: "completed",
    priority: 58,
    assignedQueue: "Q-005",
    assignedAnalyst: "A-005",
    createdAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-024",
    reference: "SE-2024-024",
    customerName: "Stockholm Ventures AB",
    country: "Sweden",
    numberOfKP: 6,
    numberOfDocuments: 17,
    cashAmount: 540000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 5,
    queryResponseTime: 9,
    customerBehavior: "responsive",
    status: "pending",
    priority: 71,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 23).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-025",
    reference: "UK-2024-025",
    customerName: "Oxford Research Institute",
    country: "United Kingdom",
    numberOfKP: 14,
    numberOfDocuments: 52,
    cashAmount: 4200000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 1,
    queryResponseTime: 2,
    customerBehavior: "responsive",
    status: "in_progress",
    priority: 99,
    assignedQueue: "Q-004",
    assignedAnalyst: "A-003",
    createdAt: new Date(Date.now() - 86400000 * 24).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-026",
    reference: "CH-2024-026",
    customerName: "Zurich Banking Group",
    country: "Switzerland",
    numberOfKP: 9,
    numberOfDocuments: 30,
    cashAmount: 1800000,
    isUKBased: false,
    isComplex: true,
    submissionSpeed: 3,
    queryResponseTime: 5,
    customerBehavior: "responsive",
    status: "pending",
    priority: 92,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 26).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-027",
    reference: "UK-2024-027",
    customerName: "Liverpool Property Developers",
    country: "United Kingdom",
    numberOfKP: 5,
    numberOfDocuments: 14,
    cashAmount: 380000,
    isUKBased: true,
    isComplex: false,
    submissionSpeed: 6,
    queryResponseTime: 11,
    customerBehavior: "responsive",
    status: "pending",
    priority: 63,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 27).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-028",
    reference: "BR-2024-028",
    customerName: "São Paulo Trading Ltda",
    country: "Brazil",
    numberOfKP: 4,
    numberOfDocuments: 10,
    cashAmount: 260000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 12,
    queryResponseTime: 24,
    customerBehavior: "poor",
    status: "pending",
    priority: 25,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 28).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-029",
    reference: "UK-2024-029",
    customerName: "Cambridge Technology Group",
    country: "United Kingdom",
    numberOfKP: 8,
    numberOfDocuments: 26,
    cashAmount: 920000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 3,
    queryResponseTime: 5,
    customerBehavior: "responsive",
    status: "pending",
    priority: 86,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 29).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-030",
    reference: "IN-2024-030",
    customerName: "Mumbai Enterprises Pvt",
    country: "India",
    numberOfKP: 5,
    numberOfDocuments: 15,
    cashAmount: 410000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 9,
    queryResponseTime: 17,
    customerBehavior: "slow",
    status: "pending",
    priority: 41,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-031",
    reference: "UK-2024-031",
    customerName: "Nottingham Healthcare Ltd",
    country: "United Kingdom",
    numberOfKP: 6,
    numberOfDocuments: 18,
    cashAmount: 520000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 4,
    queryResponseTime: 8,
    customerBehavior: "responsive",
    status: "completed",
    priority: 76,
    assignedQueue: "Q-001",
    assignedAnalyst: "A-002",
    createdAt: new Date(Date.now() - 86400000 * 35).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-032",
    reference: "NO-2024-032",
    customerName: "Oslo Energy AS",
    country: "Norway",
    numberOfKP: 7,
    numberOfDocuments: 21,
    cashAmount: 780000,
    isUKBased: false,
    isComplex: true,
    submissionSpeed: 5,
    queryResponseTime: 9,
    customerBehavior: "responsive",
    status: "pending",
    priority: 74,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 31).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-033",
    reference: "UK-2024-033",
    customerName: "Sheffield Steel Industries",
    country: "United Kingdom",
    numberOfKP: 13,
    numberOfDocuments: 48,
    cashAmount: 3600000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 2,
    queryResponseTime: 4,
    customerBehavior: "responsive",
    status: "in_progress",
    priority: 98,
    assignedQueue: "Q-004",
    assignedAnalyst: "A-001",
    createdAt: new Date(Date.now() - 86400000 * 32).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-034",
    reference: "AE-2024-034",
    customerName: "Dubai Investment Corp",
    country: "United Arab Emirates",
    numberOfKP: 10,
    numberOfDocuments: 32,
    cashAmount: 2400000,
    isUKBased: false,
    isComplex: true,
    submissionSpeed: 4,
    queryResponseTime: 7,
    customerBehavior: "responsive",
    status: "pending",
    priority: 93,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 33).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-035",
    reference: "UK-2024-035",
    customerName: "Brighton Hospitality Group",
    country: "United Kingdom",
    numberOfKP: 4,
    numberOfDocuments: 11,
    cashAmount: 290000,
    isUKBased: true,
    isComplex: false,
    submissionSpeed: 5,
    queryResponseTime: 10,
    customerBehavior: "responsive",
    status: "pending",
    priority: 62,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 34).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-036",
    reference: "MX-2024-036",
    customerName: "Mexico City Holdings SA",
    country: "Mexico",
    numberOfKP: 3,
    numberOfDocuments: 9,
    cashAmount: 210000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 10,
    queryResponseTime: 19,
    customerBehavior: "slow",
    status: "pending",
    priority: 36,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 36).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-037",
    reference: "UK-2024-037",
    customerName: "Aberdeen Oil Services",
    country: "United Kingdom",
    numberOfKP: 11,
    numberOfDocuments: 38,
    cashAmount: 2600000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 3,
    queryResponseTime: 5,
    customerBehavior: "responsive",
    status: "pending",
    priority: 95,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 37).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-038",
    reference: "BE-2024-038",
    customerName: "Brussels Finance NV",
    country: "Belgium",
    numberOfKP: 5,
    numberOfDocuments: 14,
    cashAmount: 460000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 6,
    queryResponseTime: 12,
    customerBehavior: "responsive",
    status: "pending",
    priority: 67,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 38).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-039",
    reference: "UK-2024-039",
    customerName: "Plymouth Marine Engineering",
    country: "United Kingdom",
    numberOfKP: 7,
    numberOfDocuments: 22,
    cashAmount: 740000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 4,
    queryResponseTime: 7,
    customerBehavior: "responsive",
    status: "completed",
    priority: 80,
    assignedQueue: "Q-001",
    assignedAnalyst: "A-005",
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-040",
    reference: "ZA-2024-040",
    customerName: "Cape Town Trading Co",
    country: "South Africa",
    numberOfKP: 4,
    numberOfDocuments: 12,
    cashAmount: 310000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 8,
    queryResponseTime: 16,
    customerBehavior: "slow",
    status: "pending",
    priority: 43,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 39).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-041",
    reference: "UK-2024-041",
    customerName: "York Heritage Trust",
    country: "United Kingdom",
    numberOfKP: 6,
    numberOfDocuments: 19,
    cashAmount: 580000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 3,
    queryResponseTime: 6,
    customerBehavior: "responsive",
    status: "pending",
    priority: 79,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 41).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-042",
    reference: "DK-2024-042",
    customerName: "Copenhagen Shipping A/S",
    country: "Denmark",
    numberOfKP: 8,
    numberOfDocuments: 25,
    cashAmount: 860000,
    isUKBased: false,
    isComplex: true,
    submissionSpeed: 5,
    queryResponseTime: 10,
    customerBehavior: "responsive",
    status: "pending",
    priority: 73,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 42).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-043",
    reference: "UK-2024-043",
    customerName: "Leicester Pharmaceuticals",
    country: "United Kingdom",
    numberOfKP: 9,
    numberOfDocuments: 29,
    cashAmount: 1400000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 2,
    queryResponseTime: 4,
    customerBehavior: "responsive",
    status: "in_progress",
    priority: 90,
    assignedQueue: "Q-001",
    assignedAnalyst: "A-002",
    createdAt: new Date(Date.now() - 86400000 * 43).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-044",
    reference: "IE-2024-044",
    customerName: "Dublin Tech Solutions",
    country: "Ireland",
    numberOfKP: 5,
    numberOfDocuments: 13,
    cashAmount: 390000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 7,
    queryResponseTime: 13,
    customerBehavior: "slow",
    status: "pending",
    priority: 47,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 44).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-045",
    reference: "UK-2024-045",
    customerName: "Coventry Automotive Ltd",
    country: "United Kingdom",
    numberOfKP: 10,
    numberOfDocuments: 34,
    cashAmount: 1900000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 3,
    queryResponseTime: 5,
    customerBehavior: "responsive",
    status: "pending",
    priority: 94,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-046",
    reference: "AT-2024-046",
    customerName: "Vienna Investment AG",
    country: "Austria",
    numberOfKP: 6,
    numberOfDocuments: 16,
    cashAmount: 620000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 6,
    queryResponseTime: 11,
    customerBehavior: "responsive",
    status: "pending",
    priority: 69,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 46).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-047",
    reference: "UK-2024-047",
    customerName: "Swansea Renewable Energy",
    country: "United Kingdom",
    numberOfKP: 12,
    numberOfDocuments: 42,
    cashAmount: 3100000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 2,
    queryResponseTime: 3,
    customerBehavior: "responsive",
    status: "pending",
    priority: 97,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 47).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-048",
    reference: "PL-2024-048",
    customerName: "Warsaw Manufacturing Sp zoo",
    country: "Poland",
    numberOfKP: 4,
    numberOfDocuments: 11,
    cashAmount: 280000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 9,
    queryResponseTime: 18,
    customerBehavior: "slow",
    status: "pending",
    priority: 39,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 48).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-049",
    reference: "UK-2024-049",
    customerName: "Reading Digital Services",
    country: "United Kingdom",
    numberOfKP: 5,
    numberOfDocuments: 14,
    cashAmount: 410000,
    isUKBased: true,
    isComplex: false,
    submissionSpeed: 4,
    queryResponseTime: 8,
    customerBehavior: "responsive",
    status: "completed",
    priority: 64,
    assignedQueue: "Q-005",
    assignedAnalyst: "A-004",
    createdAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-050",
    reference: "HK-2024-050",
    customerName: "Hong Kong Ventures Ltd",
    country: "Hong Kong",
    numberOfKP: 7,
    numberOfDocuments: 23,
    cashAmount: 820000,
    isUKBased: false,
    isComplex: true,
    submissionSpeed: 5,
    queryResponseTime: 9,
    customerBehavior: "responsive",
    status: "pending",
    priority: 75,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 49).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-051",
    reference: "UK-2024-051",
    customerName: "Exeter Financial Holdings",
    country: "United Kingdom",
    numberOfKP: 8,
    numberOfDocuments: 27,
    cashAmount: 1100000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 3,
    queryResponseTime: 6,
    customerBehavior: "responsive",
    status: "in_progress",
    priority: 87,
    assignedQueue: "Q-001",
    assignedAnalyst: "A-003",
    createdAt: new Date(Date.now() - 86400000 * 51).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-052",
    reference: "NZ-2024-052",
    customerName: "Auckland Trading Ltd",
    country: "New Zealand",
    numberOfKP: 4,
    numberOfDocuments: 10,
    cashAmount: 330000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 8,
    queryResponseTime: 15,
    customerBehavior: "slow",
    status: "pending",
    priority: 45,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 52).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-053",
    reference: "UK-2024-053",
    customerName: "Derby Construction Group",
    country: "United Kingdom",
    numberOfKP: 6,
    numberOfDocuments: 17,
    cashAmount: 560000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 4,
    queryResponseTime: 7,
    customerBehavior: "responsive",
    status: "pending",
    priority: 77,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 53).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-054",
    reference: "FI-2024-054",
    customerName: "Helsinki Tech Oy",
    country: "Finland",
    numberOfKP: 5,
    numberOfDocuments: 15,
    cashAmount: 480000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 6,
    queryResponseTime: 11,
    customerBehavior: "responsive",
    status: "pending",
    priority: 66,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 54).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-055",
    reference: "UK-2024-055",
    customerName: "Bath Luxury Hotels",
    country: "United Kingdom",
    numberOfKP: 9,
    numberOfDocuments: 31,
    cashAmount: 1700000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 2,
    queryResponseTime: 4,
    customerBehavior: "responsive",
    status: "pending",
    priority: 91,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 55).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-056",
    reference: "PT-2024-056",
    customerName: "Lisbon Property Investments",
    country: "Portugal",
    numberOfKP: 3,
    numberOfDocuments: 9,
    cashAmount: 240000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 10,
    queryResponseTime: 20,
    customerBehavior: "slow",
    status: "pending",
    priority: 35,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 56).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-057",
    reference: "UK-2024-057",
    customerName: "Preston Technology Park",
    country: "United Kingdom",
    numberOfKP: 7,
    numberOfDocuments: 21,
    cashAmount: 720000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 3,
    queryResponseTime: 6,
    customerBehavior: "responsive",
    status: "completed",
    priority: 81,
    assignedQueue: "Q-001",
    assignedAnalyst: "A-001",
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-058",
    reference: "CZ-2024-058",
    customerName: "Prague Manufacturing sro",
    country: "Czech Republic",
    numberOfKP: 5,
    numberOfDocuments: 13,
    cashAmount: 370000,
    isUKBased: false,
    isComplex: false,
    submissionSpeed: 7,
    queryResponseTime: 14,
    customerBehavior: "slow",
    status: "pending",
    priority: 48,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 57).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-059",
    reference: "UK-2024-059",
    customerName: "Wolverhampton Industrial Estate",
    country: "United Kingdom",
    numberOfKP: 11,
    numberOfDocuments: 39,
    cashAmount: 2500000,
    isUKBased: true,
    isComplex: true,
    submissionSpeed: 2,
    queryResponseTime: 4,
    customerBehavior: "responsive",
    status: "in_progress",
    priority: 96,
    assignedQueue: "Q-004",
    assignedAnalyst: "A-002",
    createdAt: new Date(Date.now() - 86400000 * 58).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "APP-060",
    reference: "UK-2024-060",
    customerName: "Canterbury Heritage Projects",
    country: "United Kingdom",
    numberOfKP: 4,
    numberOfDocuments: 12,
    cashAmount: 340000,
    isUKBased: true,
    isComplex: false,
    submissionSpeed: 5,
    queryResponseTime: 9,
    customerBehavior: "responsive",
    status: "pending",
    priority: 61,
    assignedQueue: null,
    assignedAnalyst: null,
    createdAt: new Date(Date.now() - 86400000 * 59).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockQueues: Queue[] = [
  {
    id: "Q-001",
    name: "High Priority - UK Complex",
    description: "UK-based complex applications with high value",
    color: "#5A287F", // NatWest Purple
    maxCapacity: 100,
    analystIds: [],
    applicationCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "Q-002",
    name: "Standard - International",
    description: "International applications with standard complexity",
    color: "#8B5FA8", // Light Purple
    maxCapacity: 150,
    analystIds: [],
    applicationCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "Q-003",
    name: "Fast Track - Responsive",
    description: "Quick turnaround applications with responsive customers",
    color: "#B388CC", // Lighter Purple
    maxCapacity: 120,
    analystIds: [],
    applicationCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "Q-004",
    name: "High Value",
    description: "Applications over £1M requiring specialist review",
    color: "#6B3FA0", // Medium Purple
    maxCapacity: 80,
    analystIds: [],
    applicationCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "Q-005",
    name: "Standard - UK",
    description: "Standard UK applications",
    color: "#9B72B8", // Mid-light Purple
    maxCapacity: 200,
    analystIds: [],
    applicationCount: 0,
    createdAt: new Date().toISOString(),
  },
]

export const mockAnalysts: Analyst[] = [
  {
    id: "A-001",
    name: "Sarah Johnson",
    email: "sarah.johnson@natwest.com",
    role: "analyst",
    queueIds: [],
    workload: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "A-002",
    name: "Michael Chen",
    email: "michael.chen@natwest.com",
    role: "analyst",
    queueIds: [],
    workload: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "A-003",
    name: "Emily Roberts",
    email: "emily.roberts@natwest.com",
    role: "analyst",
    queueIds: [],
    workload: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "A-004",
    name: "David Kumar",
    email: "david.kumar@natwest.com",
    role: "manager",
    queueIds: [],
    workload: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "A-005",
    name: "Jessica Lee",
    email: "jessica.lee@natwest.com",
    role: "analyst",
    queueIds: [],
    workload: 0,
    createdAt: new Date().toISOString(),
  },
]

export const mockRules: Rule[] = [
  {
    id: "R-001",
    name: "Ultra High Value - Specialist Review",
    priority: 1,
    isActive: true,
    conditions: [{ field: "cashAmount", operator: "greater_than", value: 1000000 }],
    actions: { bucketId: "Q-004", priorityScore: 95 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-002",
    name: "UK Complex High Value Priority",
    priority: 2,
    isActive: true,
    conditions: [
      { field: "isUKBased", operator: "equals", value: true },
      { field: "isComplex", operator: "equals", value: true },
      { field: "cashAmount", operator: "greater_than", value: 500000 },
    ],
    actions: { bucketId: "Q-001", priorityScore: 90 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-003",
    name: "International High Value Complex",
    priority: 3,
    isActive: true,
    conditions: [
      { field: "isUKBased", operator: "equals", value: false },
      { field: "isComplex", operator: "equals", value: true },
      { field: "cashAmount", operator: "greater_than", value: 500000 },
    ],
    actions: { bucketId: "Q-002", priorityScore: 85 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-004",
    name: "Fast Track Responsive Customers",
    priority: 4,
    isActive: true,
    conditions: [
      { field: "customerBehavior", operator: "equals", value: "responsive" },
      { field: "submissionSpeed", operator: "less_than", value: 6 },
      { field: "queryResponseTime", operator: "less_than", value: 10 },
    ],
    actions: { bucketId: "Q-003", priorityScore: 80 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-005",
    name: "UK Complex Medium Value",
    priority: 5,
    isActive: true,
    conditions: [
      { field: "isUKBased", operator: "equals", value: true },
      { field: "isComplex", operator: "equals", value: true },
      { field: "cashAmount", operator: "less_than", value: 500000 },
    ],
    actions: { bucketId: "Q-001", priorityScore: 75 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-006",
    name: "High Document Volume",
    priority: 6,
    isActive: true,
    conditions: [
      { field: "numberOfDocuments", operator: "greater_than", value: 30 },
      { field: "numberOfKP", operator: "greater_than", value: 8 },
    ],
    actions: { bucketId: "Q-004", priorityScore: 88 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-007",
    name: "UK Standard Applications",
    priority: 7,
    isActive: true,
    conditions: [
      { field: "isUKBased", operator: "equals", value: true },
      { field: "isComplex", operator: "equals", value: false },
    ],
    actions: { bucketId: "Q-005", priorityScore: 60 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-008",
    name: "International Standard Applications",
    priority: 8,
    isActive: true,
    conditions: [
      { field: "isUKBased", operator: "equals", value: false },
      { field: "isComplex", operator: "equals", value: false },
    ],
    actions: { bucketId: "Q-002", priorityScore: 50 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-009",
    name: "Low Priority - Poor Customer Behavior",
    priority: 9,
    isActive: true,
    conditions: [
      { field: "customerBehavior", operator: "equals", value: "poor" },
      { field: "queryResponseTime", operator: "greater_than", value: 20 },
    ],
    actions: { bucketId: "Q-002", priorityScore: 25 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-010",
    name: "Medium Value Responsive International",
    priority: 10,
    isActive: true,
    conditions: [
      { field: "isUKBased", operator: "equals", value: false },
      { field: "customerBehavior", operator: "equals", value: "responsive" },
      { field: "cashAmount", operator: "greater_than", value: 300000 },
    ],
    actions: { bucketId: "Q-003", priorityScore: 70 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-011",
    name: "Slow Response - Standard Priority",
    priority: 11,
    isActive: true,
    conditions: [
      { field: "customerBehavior", operator: "equals", value: "slow" },
      { field: "submissionSpeed", operator: "greater_than", value: 8 },
    ],
    actions: { bucketId: "Q-002", priorityScore: 40 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "R-012",
    name: "High KP Count - Complex Review",
    priority: 12,
    isActive: true,
    conditions: [{ field: "numberOfKP", operator: "greater_than", value: 10 }],
    actions: { bucketId: "Q-001", priorityScore: 82 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
